name: Deploy to Railway Dev Environment 

on: 
  push:
    branches: [develop]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: action/setup-node@v1
        with:
          node-version: 16.x

      - name: install packages
        run: npm install

      - name: install Railway
        run: npm im-g @railway/cli

      - name: Deploy
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_DEV_TOKEN }}